-- MySQL Script generated by MySQL Workbench
-- 06/10/15 19:05:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema odontoifma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema odontoifma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `odontoifma` DEFAULT CHARACTER SET utf8 ;
USE `odontoifma` ;

-- -----------------------------------------------------
-- Table `odontoifma`.`tipo_operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`tipo_operador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `odontoifma`.`operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`operador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `documento` VARCHAR(255) NULL DEFAULT NULL,
  `tipo_operador` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `tipo_operador`),
  UNIQUE INDEX `idoperador_UNIQUE` (`id` ASC),
  INDEX `fk_operador_tipo_operador1_idx` (`tipo_operador` ASC),
  CONSTRAINT `fk_operador_tipo_operador1`
    FOREIGN KEY (`tipo_operador`)
    REFERENCES `odontoifma`.`tipo_operador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `odontoifma`.`acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`acesso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `operador_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `operador_id`),
  INDEX `fk_acesso_operador1_idx` (`operador_id` ASC),
  CONSTRAINT `fk_acesso_operador1`
    FOREIGN KEY (`operador_id`)
    REFERENCES `odontoifma`.`operador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `odontoifma`.`campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`campus` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `odontoifma`.`tipo_paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`tipo_paciente` (
  `id` INT(11) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `odontoifma`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`paciente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `turma` VARCHAR(255) NOT NULL,
  `naturalidade` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(255) NOT NULL,
  `sexo` VARCHAR(255) NOT NULL,
  `raca` VARCHAR(255) NOT NULL,
  `matricula` VARCHAR(255) NULL DEFAULT NULL,
  `campus_id` INT(11) NOT NULL,
  `tipo_paciente_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `campus_id`, `tipo_paciente_id`),
  UNIQUE INDEX `idpaciente_UNIQUE` (`id` ASC),
  INDEX `fk_paciente_campus1_idx` (`campus_id` ASC),
  INDEX `fk_paciente_tipo_paciente1_idx` (`tipo_paciente_id` ASC),
  CONSTRAINT `fk_paciente_campus1`
    FOREIGN KEY (`campus_id`)
    REFERENCES `odontoifma`.`campus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_tipo_paciente1`
    FOREIGN KEY (`tipo_paciente_id`)
    REFERENCES `odontoifma`.`tipo_paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `odontoifma`.`queixa_principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`queixa_principal` (
  `idqueixa_principal` INT NOT NULL AUTO_INCREMENT,
  `queixa` VARCHAR(255) NOT NULL,
  `paciente` INT NOT NULL,
  PRIMARY KEY (`idqueixa_principal`, `paciente`),
  INDEX `fk_queixa_principal_paciente_idx` (`paciente` ASC),
  CONSTRAINT `fk_queixa_principal_paciente`
    FOREIGN KEY (`paciente`)
    REFERENCES `odontoifma`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontoifma`.`doencas_preexistentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`doencas_preexistentes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontoifma`.`historia_medica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`historia_medica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `doenca_preexistente` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `qual` VARCHAR(255) NULL,
  `paciente` INT NOT NULL,
  PRIMARY KEY (`id`, `doenca_preexistente`, `paciente`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_historia_medica_doencas_preexistentes_idx` (`doenca_preexistente` ASC),
  INDEX `fk_historia_medica_paciente_idx` (`paciente` ASC),
  CONSTRAINT `fk_historia_medica_doencas_preexistentes`
    FOREIGN KEY (`doenca_preexistente`)
    REFERENCES `odontoifma`.`doencas_preexistentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historia_medica_paciente`
    FOREIGN KEY (`paciente`)
    REFERENCES `odontoifma`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontoifma`.`higiene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`higiene` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paciente` INT NOT NULL,
  `escovacao` INT NULL,
  `fio_dental` TINYINT(1) NOT NULL,
  `bochecho` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`, `paciente`),
  INDEX `fk_higiene_paciente_idx` (`paciente` ASC),
  CONSTRAINT `fk_higiene_paciente`
    FOREIGN KEY (`paciente`)
    REFERENCES `odontoifma`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontoifma`.`tipo_habito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`tipo_habito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontoifma`.`parafuncionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`parafuncionais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `habito` INT NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `paciente` INT NOT NULL,
  PRIMARY KEY (`id`, `paciente`, `habito`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_parafuncionais_tipo_habito_idx` (`habito` ASC),
  INDEX `fk_parafuncionais_paciente_idx` (`paciente` ASC),
  CONSTRAINT `fk_parafuncionais_tipo_habito`
    FOREIGN KEY (`habito`)
    REFERENCES `odontoifma`.`tipo_habito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parafuncionais_paciente`
    FOREIGN KEY (`paciente`)
    REFERENCES `odontoifma`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
