-- MySQL Script generated by MySQL Workbench
-- Ter 26 Mai 2015 18:46:15 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema odontoifma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema odontoifma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `odontoifma`
  DEFAULT CHARACTER SET utf8
  COLLATE utf8_general_ci;
USE `odontoifma`;

-- -----------------------------------------------------
-- Table `odontoifma`.`campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`campus` (
  `id`   INT          NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontoifma`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`paciente` (
  `id`           INT          NOT NULL AUTO_INCREMENT,
  `nome`         VARCHAR(255) NOT NULL,
  `data_nasc`    DATE         NOT NULL,
  `turma`        VARCHAR(255) NOT NULL,
  `naturalidade` VARCHAR(255) NOT NULL,
  `telefone`     VARCHAR(255) NOT NULL,
  `sexo`         VARCHAR(255) NOT NULL,
  `raca`         VARCHAR(255) NOT NULL,
  `matricula`    VARCHAR(255) NULL,
  `campus_id`    INT          NOT NULL,
  PRIMARY KEY (`id`, `campus_id`),
  UNIQUE INDEX `idpaciente_UNIQUE` (`id` ASC),
  INDEX `fk_paciente_campus1_idx` (`campus_id` ASC),
  CONSTRAINT `fk_paciente_campus1`
  FOREIGN KEY (`campus_id`)
  REFERENCES `odontoifma`.`campus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontoifma`.`tipo_operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`tipo_operador` (
  `id`        INT          NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontoifma`.`operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`operador` (
  `id`            INT          NOT NULL AUTO_INCREMENT,
  `nome`          VARCHAR(255) NOT NULL,
  `documento`     VARCHAR(255) NULL,
  `tipo_operador` INT          NOT NULL,
  PRIMARY KEY (`id`, `tipo_operador`),
  UNIQUE INDEX `idoperador_UNIQUE` (`id` ASC),
  INDEX `fk_operador_tipo_operador1_idx` (`tipo_operador` ASC),
  CONSTRAINT `fk_operador_tipo_operador1`
  FOREIGN KEY (`tipo_operador`)
  REFERENCES `odontoifma`.`tipo_operador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `odontoifma`.`acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `odontoifma`.`acesso` (
  `id`          INT          NOT NULL,
  `login`       VARCHAR(255) NOT NULL,
  `senha`       VARCHAR(255) NOT NULL,
  `operador_id` INT          NOT NULL,
  PRIMARY KEY (`id`, `operador_id`),
  INDEX `fk_acesso_operador1_idx` (`operador_id` ASC),
  CONSTRAINT `fk_acesso_operador1`
  FOREIGN KEY (`operador_id`)
  REFERENCES `odontoifma`.`operador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
